INSERT INTO MEMBERS VALUES ('mem-'||trim(to_char(MEM_SEQ.nextval,'0000')), 
							'scott','tiger','콘서트가고싶다','scott@tiger.com','profileimg/pimg1.jpg',0, sysdate);
							
						
INSERT INTO members(memid, mempw, MEMMAIL) values('man', 'hi', 'man@naver.com');
					
SELECT * FROM MEMBERs;




ALTER TABLE MEMBERS 
MODIFY mempoint DEFAULT 0;

ALTER TABLE MEMBERS MODIFY(memnum VARCHAR2(9));
ALTER TABLE MEMBERS 
MODIFY memnum DEFAULT 'mem-'||trim(to_char(MEM_SEQ.nextval,'0000'));
ALTER TABLE MEMBERS MODIFY memnum DEFAULT NULL;

SELECT LENGTH(memnum) FROM members;

ALTER TABLE MEMBERS 
MODIFY memnick DEFAULT '닉네임'||trim(to_char(MEM_SEQ.nextval,'0000'));

ALTER TABLE MEMBERS 
ADD joinDate date;

ALTER TABLE MEMBERS 
ADD auth number;
ALTER TABLE MEMBERS MODIFY auth DEFAULT 0;
ALTER TABLE members
ADD CONSTRAINT MEMBERS_AUTH_CHK CHECK(auth>=0 AND auth<=10);



ALTER TABLE MEMBERS 
MODIFY joinDate DEFAULT sysdate;

ALTER TABLE TEST1.MEMBERS DROP CONSTRAINT MEMBERS_MEMNUM_UQ;
ALTER TABLE TEST1.MEMBERS DROP CONSTRAINT sys_c007435;

ALTER TABLE MEMBERS 


ADD CONSTRAINT MEMBERS_MEMID_UQ UNIQUE(memID);
ALTER TABLE MEMBERS 
MODIFY memid CONSTRAINT members_memid_NN NOT NULL; 

ALTER TABLE MEMBERS 
MODIFY mempw CONSTRAINT members_mempw_NN NOT NULL; 
 
ALTER TABLE MEMBERS 
MODIFY memmail CONSTRAINT members_memmail_NN NOT NULL; 

ALTER TABLE MEMBERS 
ADD CONSTRAINT MEMBERS_MEMMAIL_UQ UNIQUE(memmail);
